### ISSUE TITLE
Drop Django 3.1 from requirements 

### ISSUE THREAD

**Issue by marksweb** [django-cms/django-cms-quickstart#24]
Support for Django 3.1 ended early December 2021, so I see two choices.

We either drop back to 2.2 which ends LTS in April, or we move to 3.2 and drop admin style.

**Comment by macolo** [comment]
@marksweb I think we should drop admin style - this has been discussed as a possible way of action for a while, we should bring it up again. Ill create a branch here to see how it looks.

**Comment by marksweb** [comment]
@macolo There's actually been some work done in the past week or so on brining a dark theme to cms and admin-style. So it might be worth giving that a little time as I think it's ready to review or at least test.

**Comment by crydotsnake** [comment]
Hello,

I think we can close this issue. Because we have Django version 3.2.13 in the quickstart now.
