### ISSUE TITLE
uWSGI not support in windows

### ISSUE THREAD

**Issue by Mohammadwh** [django-cms/django-cms-quickstart#42]
(venv) E:\cms>pip install -r requirements.txt
Collecting asgiref==3.5.2
  Using cached asgiref-3.5.2-py3-none-any.whl (22 kB)
Collecting boto3==1.14.49
  Using cached boto3-1.14.49-py2.py3-none-any.whl (129 kB)
Collecting botocore==1.17.63
  Using cached botocore-1.17.63-py2.py3-none-any.whl (6.6 MB)
Collecting build==0.8.0
  Using cached build-0.8.0-py3-none-any.whl (17 kB)
Collecting click==8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting cssselect2==0.7.0
  Using cached cssselect2-0.7.0-py3-none-any.whl (15 kB)
Collecting dj-database-url==0.5.0
  Using cached dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
Collecting django==3.2
  Using cached Django-3.2-py3-none-any.whl (7.9 MB)
Collecting django-appconf==1.0.5
  Using cached django_appconf-1.0.5-py3-none-any.whl (6.4 kB)
Collecting django-classy-tags==3.0.1
  Using cached django_classy_tags-3.0.1-py3-none-any.whl (14 kB)
Collecting django-cms==3.11.0
  Using cached django_cms-3.11.0-py2.py3-none-any.whl (2.1 MB)
Collecting django-entangled==0.4
  Using cached django-entangled-0.4.tar.gz (10 kB)
Collecting django-filer==2.2.3
  Using cached django_filer-2.2.3-py3-none-any.whl (1.1 MB)
Collecting django-formtools==2.3
  Using cached django_formtools-2.3-py3-none-any.whl (148 kB)
Collecting django-js-asset==2.0.0
  Using cached django_js_asset-2.0.0-py3-none-any.whl (4.9 kB)
Collecting django-mptt==0.13.4
  Using cached django_mptt-0.13.4-py3-none-any.whl (137 kB)
Collecting django-polymorphic==3.1.0
  Using cached django_polymorphic-3.1.0-py3-none-any.whl (63 kB)
Collecting django-sekizai==4.0.0
  Using cached django_sekizai-4.0.0-py3-none-any.whl (8.6 kB)
Collecting django-select2==7.10.1
  Using cached django_select2-7.10.1-py2.py3-none-any.whl (14 kB)
Collecting django-storage-url==0.5.0
  Using cached django_storage_url-0.5.0-py2.py3-none-any.whl (6.5 kB)
Collecting django-storages==1.13.1
  Using cached django_storages-1.13.1-py3-none-any.whl (46 kB)
Collecting django-treebeard==4.4
  Using cached django_treebeard-4.4-py3-none-any.whl (103 kB)
Collecting djangocms-admin-style==3.2.0
  Using cached djangocms_admin_style-3.2.0-py3-none-any.whl (406 kB)
Collecting djangocms-attributes-field==2.1.0
  Using cached djangocms_attributes_field-2.1.0-py3-none-any.whl (16 kB)
Collecting djangocms-file==3.0.0
  Using cached djangocms_file-3.0.0-py3-none-any.whl (140 kB)
Collecting djangocms-frontend==1.0.0
  Using cached djangocms_frontend-1.0.0-py3-none-any.whl (296 kB)
Collecting djangocms-googlemap==2.0.0
  Using cached djangocms_googlemap-2.0.0-py3-none-any.whl (217 kB)
Collecting djangocms-icon==2.0.0
  Using cached djangocms_icon-2.0.0-py3-none-any.whl (162 kB)
Collecting djangocms-picture==3.0.0
  Using cached djangocms_picture-3.0.0-py3-none-any.whl (208 kB)
Collecting djangocms-style==3.0.0
  Using cached djangocms_style-3.0.0-py3-none-any.whl (127 kB)
Collecting djangocms-text-ckeditor==5.1.1
  Using cached djangocms_text_ckeditor-5.1.1-py3-none-any.whl (2.1 MB)
Collecting djangocms-video==3.0.0
  Using cached djangocms_video-3.0.0-py3-none-any.whl (165 kB)
Collecting docutils==0.15.2
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting easy-thumbnails[svg]==2.8.3
  Using cached easy_thumbnails-2.8.3-py3-none-any.whl (75 kB)
Collecting furl==2.1.3
  Using cached furl-2.1.3-py2.py3-none-any.whl (20 kB)
Collecting html5lib==1.1
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting jmespath==0.10.0
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting lxml==4.9.1
  Using cached lxml-4.9.1-cp310-cp310-win_amd64.whl (3.6 MB)
Collecting orderedmultidict==1.0.1
  Using cached orderedmultidict-1.0.1-py2.py3-none-any.whl (11 kB)
Collecting packaging==21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pep517==0.13.0
  Using cached pep517-0.13.0-py3-none-any.whl (18 kB)
Collecting pillow==9.2.0
  Using cached Pillow-9.2.0-cp310-cp310-win_amd64.whl (3.3 MB)
Collecting pip-tools==6.8.0
  Using cached pip_tools-6.8.0-py3-none-any.whl (51 kB)
Collecting psycopg2==2.8.5
  Using cached psycopg2-2.8.5.tar.gz (380 kB)
Collecting pyparsing==3.0.9
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting python-dateutil==2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz==2022.2.1
  Using cached pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
Collecting reportlab==3.6.11
  Using cached reportlab-3.6.11-cp310-cp310-win_amd64.whl (2.3 MB)
Collecting s3transfer==0.3.7
  Using cached s3transfer-0.3.7-py2.py3-none-any.whl (73 kB)
Collecting six==1.16.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting sqlparse==0.4.2
  Using cached sqlparse-0.4.2-py3-none-any.whl (42 kB)
Collecting svglib==1.4.1
  Using cached svglib-1.4.1.tar.gz (913 kB)
Collecting tinycss2==1.1.1
  Using cached tinycss2-1.1.1-py3-none-any.whl (21 kB)
Collecting tomli==2.0.1
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting unidecode==1.1.2
  Using cached Unidecode-1.1.2-py2.py3-none-any.whl (239 kB)
Collecting urllib3==1.25.11
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting uwsgi==2.0.19.1
  Using cached uWSGI-2.0.19.1.tar.gz (803 kB)
    ERROR: Command errored out with exit status 1:
     command: 'E:\cms\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Negative\\AppData\\Local\\Temp\\pip-install-kecf4rfi\\uwsgi_6e72ecaf001a42c090536d95af70750f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Negative\\AppData\\Local\\Temp\\pip-install-kecf4rfi\\uwsgi_6e72ecaf001a42c090536d95af70750f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Negative\AppData\Local\Temp\pip-pip-egg-info-wi0se1se'
         cwd: C:\Users\Negative\AppData\Local\Temp\pip-install-kecf4rfi\uwsgi_6e72ecaf001a42c090536d95af70750f\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Negative\AppData\Local\Temp\pip-install-kecf4rfi\uwsgi_6e72ecaf001a42c090536d95af70750f\setup.py", line 3, in <module>
        import uwsgiconfig as uc
      File "C:\Users\Negative\AppData\Local\Temp\pip-install-kecf4rfi\uwsgi_6e72ecaf001a42c090536d95af70750f\uwsgiconfig.py", line 8, in <module>
        uwsgi_os = os.uname()[0]
    AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c7/75/45234f7b441c59b1eefd31ba3d1041a7e3c89602af24488e2a22e11e7259/uWSGI-2.0.19.1.tar.gz#sha256=faa85e053c0b1be4d5585b0858d3a511d2cd10201802e8676060fd0a109e5869 (from https://pypi.org/simple/uwsgi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement uwsgi==2.0.19.1 (from versions: 1.4.9, 1.4.10, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.9.14, 1.9.15, 1.9.16, 1.9.17, 1.9.17.1, 1.9.18, 1.9.18.1, 1.9.18.2, 1.9.19, 1.9.20, 1.9.21, 1.9.21.1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.5.1, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.11.1, 2.0.11.2, 2.0.12, 2.0.13, 2.0.13.1, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.17.1, 2.0.18, 2.0.19, 2.0.19.1, 2.0.20, 2.0.21)
ERROR: No matching distribution found for uwsgi==2.0.19.1

**Comment by zhoulei4652** [comment]
I meet the same problem, is there any solution?

**Comment by macolo** [comment]
That's why this project supports docker. Please check the Readme.

**Comment by jfmatth** [comment]
You should be able to replace with waitress-serve from the waitress project.
