### ISSUE TITLE
Documentation should be improved: How to restart server while reatining database data

### ISSUE THREAD

**Issue by MacLake** [django-cms/django-cms-quickstart#52]
The documentation lacks a description how to stop and restart the server without losing the database content. PR is following.

**Comment by MacLake** [comment]
And another documentation flaw: What’s the point in using http://django-cms-quickstart.127.0.0.1.nip.io:8000/ instead of http://127.0.0.1:8000/ (or http://localhost:8000/ ). I don’t get it, even after reading https://nip.io/ .

**Comment by WajahatKanju** [comment]
By documentation do you mean https://docs.django-cms.org/ or just the README.md

**Comment by macolo** [comment]
I can confirm that the database is retained upon `docker compose down`, `docker compose up`. The db content is not lost. Please also see #49
